
---
- hosts: all
  become: yes
  
  tasks:
    - name: installing multiple s/w
      yum: name='{{item}}' state=installed
      with_items:
             - httpd
             - tree
             - java
             - docker  
